### ISSUE TITLE
ログインしていないユーザーの権限

### ISSUE THREAD

**Issue by sunadoi** [kenkeeeenbbt/memopy#30]
ログインしていないユーザーがURLを直接入力すると該当ページが見れてしまう
エラーの原因になるので、ユーザーがログインしていない場合は、トップページにリダイレクトなどの処理を実装する

**Comment by kenkeeeenbbt** [comment]
https://github.com/kenkeeeenbbt/memopy/pull/38
で解決しました！
僕のプルリクで解決したイシューは僕がクローズすべきでしょうか？
それともイシューした人がクローズするのが普通でしょうか？
